version: '3.1'

services: 
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: f26b8ab553cfd4767216dbc7be7702fcad1b0115a6347e871faab86174d7ed4e
      POSTGRES_USER: evreka_user
      POSTGRES_DB: evreka_db
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080